### ISSUE TITLE
Register html5 on GitFund

### ISSUE THREAD

**Issue by wbb** [aredridel/html5#116]
I want suggest register you project on <a href="http://www.gitfund.org">GitFund</a>. It will help raise  money for project development.

**Comment by aredridel** [comment]
Goodness. That leaves a lot of questions unanswered -- who do you donate to when you donate to a registered project?

**Comment by wbb** [comment]
All donation go direct to project owner PayPal account. GitFund only registered donations on system & set up issue priority.

**Comment by aredridel** [comment]
Aah. I'll pass, as there's little financial incentive that would motivate me.
